// <auto-generated />
namespace TP03MainProj.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Events_And_CultureDate_Model_Modified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Events_And_CultureDate_Model_Modified));
        
        string IMigrationMetadata.Id
        {
            get { return "202404061112471_Events_And_CultureDate_Model_Modified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
